spring.application.name=gradinator

server.port=9090

spring.config.import=optional:classpath:private-info.properties
spring.datasource.url=jdbc:postgresql://localhost:5433/gradin
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

api.start-with-heartbeat=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

logging.pattern.console=%d{dd.MM HH:mm:ss.SSS} %-5level %logger{36} : %msg%n
logging.level.root=WARN
logging.level.com.pavlent1yy.gradinator=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.apache.catalina=WARN
logging.level.org.apache.coyote=WARN
logging.level.org.apache.tomcat=WARN