spring.application.name=gradinator

server.port=9090

spring.config.import=optional:classpath:private-info.properties
spring.datasource.url=jdbc:postgresql://localhost:5433/gradin
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=update