spring.security.oauth2.client.registration.vk.client-id=${VK_CLIENT_ID}
spring.security.oauth2.client.registration.vk.client-name=VK
spring.security.oauth2.client.registration.vk.client-authentication-method=none
spring.security.oauth2.client.registration.vk.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.vk.redirect-uri=${app.frontend-url}/login/oauth2/code/vk
spring.security.oauth2.client.registration.vk.scope=vkid.personal_info,email
