spring.security.oauth2.client.registration.yandex.client-id=${YANDEX_CLIENT_ID}
spring.security.oauth2.client.registration.yandex.client-secret=${YANDEX_CLIENT_SECRET}
spring.security.oauth2.client.registration.yandex.client-name=Yandex
spring.security.oauth2.client.registration.yandex.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.yandex.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.yandex.scope=login:email,login:info
spring.security.oauth2.client.registration.vk.client-id=${VK_CLIENT_ID}
spring.security.oauth2.client.registration.vk.client-name=VK
spring.security.oauth2.client.registration.vk.client-authentication-method=none
spring.security.oauth2.client.registration.vk.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.vk.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.vk.scope=vkid.personal_info,email
